### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by chawins** [arjunbhagoji/ml_defense#2]
- [ ] Add function descriptions
- [ ] Add file descriptions
- [ ] Update the README
- [ ] Include SVMs and attacks on SVMs
- [ ] Integrate DCA code
- [ ] Add other dimensionality reduction algorithms like random projections, Kernel PCA etc.
- [ ] Add functionality for other datasets
- [ ] Include more complex CNN architechtures
